### ISSUE TITLE
Prepare DDR slides

### ISSUE THREAD

**Issue by kevin-uhm** [vip-aerospace/keao#38]
Rubric:
http://rip.eng.hawaii.edu/wp-content/uploads/2020/10/me482-detailedDesignManufacturingInfo-2020f.pdf

Slides:
https://docs.google.com/presentation/u/1/d/1tc8uEN7hr7uf9jnq_b8MCX8_IMlpGKxx8C68T_yaf7k/edit?usp=drive_web&ouid=108917269640943042885

**Comment by danielley** [comment]
Presented on 10/28 to Dr. Trimble
Notes taken and recap here: https://docs.google.com/document/d/1-vjnLBqpzmcTyQa3a5DZBkUtoXzBeHEzxfw1wHG7I50/edit
Overall presentation focus was on detailed analysis and peer review, which went better according to Dr. Trimble.
