### ISSUE TITLE
Prepare for alpha prototype

### ISSUE THREAD

**Issue by kevin-uhm** [vip-aerospace/keao#39]
Rubric:
http://rip.eng.hawaii.edu/wp-content/uploads/2020/10/me482_alphaDemo_20201019.pdf

Slides/outline:
https://docs.google.com/presentation/d/1e1tInA1Q-cwwhkJBZ0s-FBb4Amnqq31993MAidjuETs/edit

**Comment by danielley** [comment]
Alpha prototype presented on 11/2 to Dr. Trimble.
Demonstrations presented:

- COMMS

- Payload

- ADCS

Notes taken during presentation: https://docs.google.com/document/d/1fqP_HQbF4hGeQdEjrIzMIw799Usxy3Qa4e0jWLRLqQk/edit
Recap Discussion Notes to be edited in after.
